//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentTracking
{
    using System;
    using System.Collections.Generic;
    
    public partial class courses
    {
        public courses()
        {
            this.groups = new HashSet<groups>();
            this.program = new HashSet<program>();
        }
    
        public int id { get; set; }
        public string course_name { get; set; }
        public Nullable<bool> is_group_enabled { get; set; }
    
        public virtual ICollection<groups> groups { get; set; }
        public virtual ICollection<program> program { get; set; }
    }
}
