//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentTracking
{
    using System;
    using System.Collections.Generic;
    
    public partial class semesters
    {
        public semesters()
        {
            this.program = new HashSet<program>();
        }
    
        public int id { get; set; }
        public string academic_year { get; set; }
        public Nullable<int> semester { get; set; }
    
        public virtual ICollection<program> program { get; set; }
    }
}
