//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentTracking
{
    using System;
    using System.Collections.Generic;
    
    public partial class teachers
    {
        public teachers()
        {
            this.program = new HashSet<program>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string email { get; set; }
        public Nullable<bool> is_admin { get; set; }
        public string password { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<program> program { get; set; }
    }
}
